/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa_combustible;

import java.awt.Color;
import java.awt.Font;
import static java.lang.Double.parseDouble;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.Queue;
import javax.swing.JFrame;

/**
 *
 * @author Camilo
 */
        
public class InterfazSurtidor extends javax.swing.JFrame implements Observer{
    
    private ArrayList<Report_File> colaReportes = new ArrayList<>(); 
    
    private String nombreProductoActual;
    private String idSurtidor = "SDOR";
    private String idSucursal="";
    private Dialog_setIp dialog;
    private Surtidor surtidor;
    private int puerto;
    private Carga_Reportes_Sucursal cola_sucursal;
    private Carga_Reportes_Central cola_central;
   
    public InterfazSurtidor() {
        setLocationRelativeTo(null);
        initComponents();
        ConexionBDCentral.setVisible(false);
        ConexionBDSuc.setVisible(false);
        EstadoCentral.setVisible(false);
        EstadoSucursal.setVisible(false);
        this.setVisible(true);
        abrirDialog("Surtidor");
        puerto = Integer.parseInt(dialog.getPuerto());
        surtidor = new Surtidor(puerto,dialog.getDireccion_ip());
        surtidor.addObserver(this);
        labelIPDataRecibe.setText(dialog.getDireccion_ip()+":"+dialog.getPuerto());
        idSurtidor+=dialog.getIdKey();
        idSurtidorField.setText(idSurtidor);    
        
        //Seteando los estados de las conexiones a conectado
        setEstadoCentral(true);   
        setEstadoSucursal(false);
          
        
        //Iniciando servicios
        Thread t = new Thread(surtidor);
        t.start();       
        cola_sucursal = new Carga_Reportes_Sucursal();
        Thread t2 = new Thread(cola_sucursal);
        cola_central = new Carga_Reportes_Central();
        Thread t3 = new Thread(cola_central);      
        t2.start();
        t3.start();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tag93 = new javax.swing.JLabel();
        text93 = new javax.swing.JTextField();
        cargar93 = new javax.swing.JButton();
        tag95 = new javax.swing.JLabel();
        text95 = new javax.swing.JTextField();
        cargar95 = new javax.swing.JButton();
        tag97 = new javax.swing.JLabel();
        text97 = new javax.swing.JTextField();
        cargar97 = new javax.swing.JButton();
        tagDiesel = new javax.swing.JLabel();
        textDiesel = new javax.swing.JTextField();
        cargarDiesel = new javax.swing.JButton();
        tagKerosene = new javax.swing.JLabel();
        textKerosene = new javax.swing.JTextField();
        cargarKerosene = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idSurtidorField = new javax.swing.JTextField();
        idSucursalField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelIPDataRecibe = new javax.swing.JLabel();
        ConexionBDCentral = new javax.swing.JLabel();
        EstadoCentral = new javax.swing.JLabel();
        ConexionBDSuc = new javax.swing.JLabel();
        EstadoSucursal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surtidor");
        setResizable(false);

        tag93.setText("93");

        text93.setFocusable(false);

        cargar93.setText("Cargar");
        cargar93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar93ActionPerformed(evt);
            }
        });

        tag95.setText("95");

        text95.setFocusable(false);

        cargar95.setText("Cargar");
        cargar95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar95ActionPerformed(evt);
            }
        });

        tag97.setText("97");

        text97.setFocusable(false);
        text97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text97ActionPerformed(evt);
            }
        });

        cargar97.setText("Cargar");
        cargar97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar97ActionPerformed(evt);
            }
        });

        tagDiesel.setText("Diesel");

        textDiesel.setFocusable(false);

        cargarDiesel.setText("Cargar");
        cargarDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDieselActionPerformed(evt);
            }
        });

        tagKerosene.setText("Kerosene");

        textKerosene.setFocusable(false);

        cargarKerosene.setText("Cargar");
        cargarKerosene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarKeroseneActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Surtidor:");

        idSurtidorField.setEditable(false);
        idSurtidorField.setFocusable(false);
        idSurtidorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSurtidorFieldActionPerformed(evt);
            }
        });

        idSucursalField.setEditable(false);
        idSucursalField.setFocusable(false);

        jLabel1.setText("ID Sucursal:");

        jLabel4.setText("Recibiendo Datos de:");

        labelIPDataRecibe.setText("IP");

        ConexionBDCentral.setText("Conexion BD Central:");
        ConexionBDCentral.setEnabled(false);

        EstadoCentral.setText("Estado");
        EstadoCentral.setEnabled(false);

        ConexionBDSuc.setText("Conexion BD Sucursal:");
        ConexionBDSuc.setEnabled(false);

        EstadoSucursal.setText("Estado");
        EstadoSucursal.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConexionBDSuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EstadoSucursal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConexionBDCentral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EstadoCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text97)
                            .addComponent(text95)
                            .addComponent(text93, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargar97)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cargar95)
                                    .addComponent(cargar93))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cargarDiesel)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tagDiesel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textKerosene, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cargarKerosene))
                                            .addComponent(tagKerosene))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tag95)
                            .addComponent(tag97)
                            .addComponent(tag93)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(idSucursalField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(idSurtidorField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(55, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIPDataRecibe)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConexionBDCentral)
                    .addComponent(EstadoCentral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConexionBDSuc)
                    .addComponent(EstadoSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tag93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargar93))
                        .addGap(18, 18, 18)
                        .addComponent(tag95)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargar95)
                            .addComponent(textKerosene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargarKerosene)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tagDiesel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargarDiesel))
                        .addGap(18, 18, 18)
                        .addComponent(tagKerosene)
                        .addGap(38, 38, 38)))
                .addComponent(tag97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargar97))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idSucursalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(idSurtidorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIPDataRecibe))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargar93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar93ActionPerformed
        // TODO add your handling code here:
        InterfazCargar interfaz = new InterfazCargar("Bencina 93", parseDouble(text93.getText()), 
                idSurtidor, idSucursal);
        interfaz.setVisible(true);
        
    }//GEN-LAST:event_cargar93ActionPerformed

    private void cargar95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar95ActionPerformed
        // TODO add your handling code here:
        InterfazCargar interfaz = new InterfazCargar("Bencina 95", parseDouble(text95.getText()), 
                idSurtidor, idSucursal);
        interfaz.setVisible(true);
    }//GEN-LAST:event_cargar95ActionPerformed

    private void cargar97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar97ActionPerformed
        // TODO add your handling code here:
        InterfazCargar interfaz = new InterfazCargar("Bencina 97", parseDouble(text97.getText()), 
                idSurtidor, idSucursal);
        interfaz.setVisible(true);      
    }//GEN-LAST:event_cargar97ActionPerformed

    private void text97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text97ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text97ActionPerformed

    private void cargarDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDieselActionPerformed
        // TODO add your handling code here:
        InterfazCargar interfaz = new InterfazCargar("Diesel", parseDouble(textDiesel.getText()), 
                idSurtidor, idSucursal);    
        interfaz.setVisible(true);
        
    }//GEN-LAST:event_cargarDieselActionPerformed

    private void cargarKeroseneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarKeroseneActionPerformed
        // TODO add your handling code here:
        InterfazCargar interfaz = new InterfazCargar("Kerosene", parseDouble(textKerosene.getText()), 
                idSurtidor, idSucursal);
        interfaz.setVisible(true);
    }//GEN-LAST:event_cargarKeroseneActionPerformed

    private void idSurtidorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSurtidorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSurtidorFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSurtidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSurtidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSurtidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSurtidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSurtidor();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConexionBDCentral;
    private javax.swing.JLabel ConexionBDSuc;
    private javax.swing.JLabel EstadoCentral;
    private javax.swing.JLabel EstadoSucursal;
    private javax.swing.JButton cargar93;
    private javax.swing.JButton cargar95;
    private javax.swing.JButton cargar97;
    private javax.swing.JButton cargarDiesel;
    private javax.swing.JButton cargarKerosene;
    private javax.swing.JTextField idSucursalField;
    private javax.swing.JTextField idSurtidorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelIPDataRecibe;
    private javax.swing.JLabel tag93;
    private javax.swing.JLabel tag95;
    private javax.swing.JLabel tag97;
    private javax.swing.JLabel tagDiesel;
    private javax.swing.JLabel tagKerosene;
    private javax.swing.JTextField text93;
    private javax.swing.JTextField text95;
    private javax.swing.JTextField text97;
    private javax.swing.JTextField textDiesel;
    private javax.swing.JTextField textKerosene;
    // End of variables declaration//GEN-END:variables
    
    private void setEstadoCentral(boolean estado){
        
        Font f= new Font("Arial", Font.BOLD, 12);
        if(estado){
            EstadoCentral.setText("Conectado");
            Color c = new Color(34, 171, 1);
            EstadoCentral.setForeground(c);
        }
        else{
            EstadoCentral.setText("Desconectado");
            EstadoCentral.setForeground(Color.RED);
        }
        EstadoCentral.setFont(f);
    }
    
    private void setEstadoSucursal(boolean estado){
        Font f= new Font("Arial", Font.BOLD, 12);
        if(estado){
            EstadoSucursal.setText("Conectado");
            Color c = new Color(34, 171, 1);
            EstadoSucursal.setForeground(c);
        }
        else{
            EstadoSucursal.setText("Desconectado");
            EstadoSucursal.setForeground(Color.RED);
        }
        EstadoSucursal.setFont(f);
    }
    private void abrirDialog(String tipo){
        
        dialog = new Dialog_setIp(this, true, tipo);
        dialog.setLocationRelativeTo(null);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);        
    }
    
    
    @Override
    public void update(Observable arg0, Object arg) {
        this.idSucursal = surtidor.getIdKeySucursal();
        this.idSucursalField.setText(this.idSucursal);
        if (arg instanceof String) {
            nombreProductoActual = (String) arg;
        }else{          
            double valor = (double) arg;
            switch(nombreProductoActual){
                case "93":
                    this.text93.setText(valor+"");
                    break;         
                case "95":
                    this.text95.setText(valor+"");
                    break;
                case "97":
                    this.text97.setText(valor+"");
                    break;
                case "diesel":
                    this.textDiesel.setText(valor+"");
                    break;
                case "kerosene":
                    this.textKerosene.setText(valor+"");
                    break;
                 
            }          
        }
    }
}
