/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa_combustible;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author mrroj
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     * @throws java.sql.SQLException
     */
    public Reportes() throws SQLException {
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        setTitle("Reportes");

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        totalVentasText = new javax.swing.JLabel();
        totalVentasField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        buttonBDCentral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonBDSSAL001 = new javax.swing.JButton();
        buttonBDSSAL002 = new javax.swing.JButton();
        buttonBDSSAL003 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sucursal", "Surtidor", "Combustible", "Precio x Litro", "Litros Cargados", "Precio Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        totalVentasText.setText("Total Ventas: $");

        totalVentasField.setEditable(false);
        totalVentasField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalVentasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVentasFieldActionPerformed(evt);
            }
        });

        closeButton.setText("Cerrar Ventana");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buttonBDCentral.setText("Central");
        buttonBDCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBDCentralActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Base de Datos:");

        buttonBDSSAL001.setText("Sucursal 001");
        buttonBDSSAL001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBDSSAL001ActionPerformed(evt);
            }
        });

        buttonBDSSAL002.setText("Sucursal 002");
        buttonBDSSAL002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBDSSAL002ActionPerformed(evt);
            }
        });

        buttonBDSSAL003.setText("Sucursal 003");
        buttonBDSSAL003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBDSSAL003ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(closeButton)
                                .addGap(277, 277, 277)
                                .addComponent(totalVentasText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalVentasField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBDCentral)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBDSSAL001)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBDSSAL002)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBDSSAL003)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBDCentral)
                    .addComponent(jLabel1)
                    .addComponent(buttonBDSSAL001)
                    .addComponent(buttonBDSSAL002)
                    .addComponent(buttonBDSSAL003))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalVentasText)
                    .addComponent(totalVentasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalVentasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVentasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalVentasFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void buttonBDCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBDCentralActionPerformed
        try {
            // TODO add your handling code here:
            iniciarTabla(0);
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBDCentralActionPerformed

    private void buttonBDSSAL001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBDSSAL001ActionPerformed
        try {
            // TODO add your handling code here:
            iniciarTabla(1);
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBDSSAL001ActionPerformed

    private void buttonBDSSAL002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBDSSAL002ActionPerformed
        try {
            // TODO add your handling code here:
            iniciarTabla(2);
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBDSSAL002ActionPerformed

    private void buttonBDSSAL003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBDSSAL003ActionPerformed
        try {
            // TODO add your handling code here:
            iniciarTabla(3);
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBDSSAL003ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Reportes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    //String1: precioLitro
    //String2: litrosCarga
    //String3: totalPagar
    //String4: ID Surtidor
    //String5: ID Sucursal
    //String6: Combustible
    
    private void iniciarTabla(int idDB) throws SQLException{
        ConexionDB datos = new ConexionDB();
        ResultSet rs = datos.getReporte(idDB);
        Double precioLitro;
        Double litrosCarga;
        Double totalPagar;
        String idSurtidor;
        String idSucursal="";
        String combustible="";
        Double totalVentas = 0.0;
        
        DefaultTableModel modelTablaVentas = (DefaultTableModel) tablaVentas.getModel();
        modelTablaVentas.setRowCount(0);
        
        while (rs.next()) {
            precioLitro = rs.getDouble(1);
            litrosCarga = rs.getDouble(2);
            totalPagar = rs.getDouble(3);
            idSurtidor = rs.getString(4);
            
            if (idDB==0){
                idSucursal = rs.getString(5);
                combustible = rs.getString(6);
            }
            if (idDB==1){
                idSucursal="SSAL01";
                combustible = rs.getString(5);
            }
            
            if (idDB==2){
                idSucursal="SSAL02";
                combustible = rs.getString(5);
            }
            
            if (idDB==3){
                idSucursal="SSAL03";
                combustible = rs.getString(5);
            }
            
            totalVentas+=totalPagar;
            
            modelTablaVentas.addRow(new Object[]{idSucursal, idSurtidor, combustible, precioLitro, litrosCarga, totalPagar});
        }
        
        totalVentasField.setText(Double.toString(totalVentas));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBDCentral;
    private javax.swing.JButton buttonBDSSAL001;
    private javax.swing.JButton buttonBDSSAL002;
    private javax.swing.JButton buttonBDSSAL003;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField totalVentasField;
    private javax.swing.JLabel totalVentasText;
    // End of variables declaration//GEN-END:variables
}
